import { readFile } from "node:fs/promises";
import assert from "node:assert/strict";

const app = await readFile(new URL("../app.js", import.meta.url), "utf8");
const fixtureB64 = (await readFile(new URL("./fixtures/zip64-fixture.zip.b64", import.meta.url), "utf8")).trim();
const fixture = Buffer.from(fixtureB64, "base64");
const sig = o => fixture.readUInt32LE(o).toString(16);
assert.equal(sig(0), "4034b50");
const findSig = hex => {
  const sig = Buffer.from(hex, "hex");
  return fixture.indexOf(sig);
};
assert.ok(findSig("504b0102") > 0, "ZIP64 fixture central directory signature missing");
assert.ok(findSig("504b0606") > 0, "ZIP64 EOCD signature missing");
assert.ok(findSig("504b0607") > 0, "ZIP64 locator signature missing");
assert.ok(findSig("504b0506") > 0, "ZIP EOCD signature missing");
assert.ok(fixture.length > 100, "ZIP64 fixture unexpectedly small");
assert.match(fixtureB64, /^UEs/);
assert.match(app, /function crc32/);
assert.match(app, /ZIP64 end-of-central-directory record/);
assert.match(app, /ZIP64 locator/);
assert.match(app, /ZIP64 extended information/);
assert.match(app, /Multi-disk ZIP/);
assert.match(app, /512 MiB browser safety limit/);
assert.match(app, /ZIP CRC check failed/);
assert.match(app, /duplicate filename/);
assert.match(app, /oldSha/);
assert.match(app, /newSha/);
assert.match(app, /VERSIONVAULT RELEASE VERIFICATION REPORT/);
console.log("VersionVault smoke checks passed.");
